dist: trusty
language: python
python:
  - 3.5
cache: pip
addons:
  postgresql: 9.5
addons:
  apt:
    packages:
      - bc
      - postgresql-9.5
      - postgresql-9.5-debversion
      - snakefood
env:
  - DJANGO=1.11 TESTENV=travis-postgresql DATABASE=ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:USER=postgres:PASSWORD=squad:HOST=127.0.0.1:PORT=5432
  - DJANGO=1.11 TESTENV=travis-sqlite3 DATABASE=
  - DJANGO=1.10 TESTENV=travis-postgresql-django1.10 DATABASE=ENGINE=django.db.backends.postgresql_psycopg2:NAME=squad:USER=postgres:PASSWORD=squad:HOST=127.0.0.1:PORT=5432
  - DJANGO=1.10 TESTENV=travis-sqlite3-django1.10 DATABASE=

before_install:
  - if test -n "$DATABASE"; then ./scripts/travis-postgresql; fi

install:
  - pip install --upgrade setuptools
  - ./scripts/travis-django
  - pip install -r requirements-dev.txt
  - pip freeze

script:
  - ./scripts/travis

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#linaro-qa"
